package entity;
// Generated 13-ene-2019 23:20:34 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order")
public class Order implements java.io.Serializable {

	private Short orderId;
	@ManyToOne
    @JoinColumn(name="user_id", nullable=false)
	private User user;
	@Column(name="refD")
	private String refD;
	@ManyToOne
    @JoinColumn(name="userId", nullable=false)
	private Set orderproducts = new HashSet(0);

	public Order() {
	}

	public Order(User user, String refD, Set orderproducts) {
		this.user = user;
		this.refD = refD;
		this.orderproducts = orderproducts;
	}

	public Short getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Short orderId) {
		this.orderId = orderId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getRefD() {
		return this.refD;
	}

	public void setRefD(String refD) {
		this.refD = refD;
	}

	public Set getOrderproducts() {
		return this.orderproducts;
	}

	public void setOrderproducts(Set orderproducts) {
		this.orderproducts = orderproducts;
	}

}
