package entity;
// Generated 13-ene-2019 23:20:34 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Orderproduct generated by hbm2java
 */
@Entity
@Table(name="orderproduct")
public class Orderproduct implements java.io.Serializable {

	private Short orderProductId;
	private Order order;
	private Product product;
	private Short quantity;
	private Set carrieses = new HashSet(0);

	public Orderproduct() {
	}

	public Orderproduct(Order order, Product product, Short quantity, Set carrieses) {
		this.order = order;
		this.product = product;
		this.quantity = quantity;
		this.carrieses = carrieses;
	}

	public Short getOrderProductId() {
		return this.orderProductId;
	}

	public void setOrderProductId(Short orderProductId) {
		this.orderProductId = orderProductId;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Short getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Short quantity) {
		this.quantity = quantity;
	}

	public Set getCarrieses() {
		return this.carrieses;
	}

	public void setCarrieses(Set carrieses) {
		this.carrieses = carrieses;
	}

}
