package entity;
// Generated 13-ene-2019 23:20:34 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product")
public class Product implements java.io.Serializable {

	private Short productId;
	private Departament departament;
	private String prodName;
	private Byte price;
	private Set orderproducts = new HashSet(0);

	public Product() {
	}

	public Product(String prodName) {
		this.prodName = prodName;
	}

	public Product(Departament departament, String prodName, Byte price, Set orderproducts) {
		this.departament = departament;
		this.prodName = prodName;
		this.price = price;
		this.orderproducts = orderproducts;
	}

	public Short getProductId() {
		return this.productId;
	}

	public void setProductId(Short productId) {
		this.productId = productId;
	}

	public Departament getDepartament() {
		return this.departament;
	}

	public void setDepartament(Departament departament) {
		this.departament = departament;
	}

	public String getProdName() {
		return this.prodName;
	}

	public void setProdName(String prodName) {
		this.prodName = prodName;
	}

	public Byte getPrice() {
		return this.price;
	}

	public void setPrice(Byte price) {
		this.price = price;
	}

	public Set getOrderproducts() {
		return this.orderproducts;
	}

	public void setOrderproducts(Set orderproducts) {
		this.orderproducts = orderproducts;
	}

}
