package entity;
// Generated 13-ene-2019 23:20:34 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user")
public class User implements java.io.Serializable {

	@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
	private Short userId;
	@Column(name="userTypeId")
	private Usertype usertype;
	@Column(name="uname")
	private String uname;
	@Column(name="password")
	private String password;
	@Column(name="rname")
	private String rname;
	@Column(name="surname")
	private String surname;
	@Column(name="mail")
	private String mail;
	@Column(name="bornDat")
	private String bornDat;
	/*@OneToMany (mappedBy="orders")
	private Set orders = new HashSet(0);
	
	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}*/

	public User() {
	}

	public User(String uname, String password, String rname, String surname, String mail) {
		this.uname = uname;
		this.password = password;
		this.rname = rname;
		this.surname = surname;
		this.mail = mail;
	}

	public User(Usertype usertype, String uname, String password, String rname, String surname, String mail,
			String bornDat/*, Set orders*/) {
		this.usertype = usertype;
		this.uname = uname;
		this.password = password;
		this.rname = rname;
		this.surname = surname;
		this.mail = mail;
		this.bornDat = bornDat;
		//this.orders = orders;
	}

	public Short getUserId() {
		return this.userId;
	}

	public void setUserId(Short userId) {
		this.userId = userId;
	}

	public Usertype getUsertype() {
		return this.usertype;
	}

	public void setUsertype(Usertype usertype) {
		this.usertype = usertype;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getBornDat() {
		return this.bornDat;
	}

	public void setBornDat(String bornDat) {
		this.bornDat = bornDat;
	}

	
	@Override
	public String toString() {
		return this.rname;
	}

}
