package probeHibernate;
// Generated 11-dic-2018 16:27:36 by Hibernate Tools 5.1.0.Alpha1

/**
 * Orderproduct generated by hbm2java
 */
public class Orderproduct implements java.io.Serializable {

	private short orderProductId;
	private Short productId;
	private Short orderId;
	private Short quantity;

	public Orderproduct() {
	}

	public Orderproduct(short orderProductId) {
		this.orderProductId = orderProductId;
	}

	public Orderproduct(short orderProductId, Short productId, Short orderId, Short quantity) {
		this.orderProductId = orderProductId;
		this.productId = productId;
		this.orderId = orderId;
		this.quantity = quantity;
	}

	public short getOrderProductId() {
		return this.orderProductId;
	}

	public void setOrderProductId(short orderProductId) {
		this.orderProductId = orderProductId;
	}

	public Short getProductId() {
		return this.productId;
	}

	public void setProductId(Short productId) {
		this.productId = productId;
	}

	public Short getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Short orderId) {
		this.orderId = orderId;
	}

	public Short getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Short quantity) {
		this.quantity = quantity;
	}

}
