package probeHibernate;
// Generated 11-dic-2018 16:27:36 by Hibernate Tools 5.1.0.Alpha1

/**
 * Authomach generated by hbm2java
 */
public class Authomach implements java.io.Serializable {

	private byte machineId;
	private String machine;
	private String description;
	private Byte segmentId;

	public Authomach() {
	}

	public Authomach(byte machineId, String machine) {
		this.machineId = machineId;
		this.machine = machine;
	}

	public Authomach(byte machineId, String machine, String description, Byte segmentId) {
		this.machineId = machineId;
		this.machine = machine;
		this.description = description;
		this.segmentId = segmentId;
	}

	public byte getMachineId() {
		return this.machineId;
	}

	public void setMachineId(byte machineId) {
		this.machineId = machineId;
	}

	public String getMachine() {
		return this.machine;
	}

	public void setMachine(String machine) {
		this.machine = machine;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Byte getSegmentId() {
		return this.segmentId;
	}

	public void setSegmentId(Byte segmentId) {
		this.segmentId = segmentId;
	}

}
