package probeHibernate;
// Generated 11-dic-2018 16:27:36 by Hibernate Tools 5.1.0.Alpha1

/**
 * Departament generated by hbm2java
 */
public class Departament implements java.io.Serializable {

	private byte departamentId;
	private String depName;
	private String description;

	public Departament() {
	}

	public Departament(byte departamentId, String depName) {
		this.departamentId = departamentId;
		this.depName = depName;
	}

	public Departament(byte departamentId, String depName, String description) {
		this.departamentId = departamentId;
		this.depName = depName;
		this.description = description;
	}

	public byte getDepartamentId() {
		return this.departamentId;
	}

	public void setDepartamentId(byte departamentId) {
		this.departamentId = departamentId;
	}

	public String getDepName() {
		return this.depName;
	}

	public void setDepName(String depName) {
		this.depName = depName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
