package probeHibernate;
// Generated 11-dic-2018 16:27:36 by Hibernate Tools 5.1.0.Alpha1

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.ManyToAny;
import org.hibernate.usertype.UserType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user")
public class User implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="userId")
	private short userId;
	@Column(name="uname")
	private String uname;
	@Column(name="password")
	private String password;
	@Column(name="rname")
	private String rname;
	@Column(name="surname")
	private String surname;
	@Column(name="mail")
	private String mail;
	@Column(name="bornDat")
	private Date bornDat;
	@Column(name="userTypeId")
	private Byte userTypeId;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userTypeId")
    private Usertype uType; 
	
	@OneToMany
	@JoinTable(joinColumns=@JoinColumn(name="order"))
	private Collection<Ordert> orders=new ArrayList<Ordert>();

	

	public User(short userId, String uname, String password, String rname, String surname, String mail,Usertype uType) {
		this.userId = userId;
		this.uname = uname;
		this.password = password;
		this.rname = rname;
		this.surname = surname;
		this.mail = mail;
		this.uType=uType;
	}

	public User(short userId, String uname, String password, String rname, String surname, String mail, Date bornDat,
		Byte userTypeId) {
		this.userId = userId;
		this.uname = uname;
		this.password = password;
		this.rname = rname;
		this.surname = surname;
		this.mail = mail;
		this.bornDat = bornDat;
		this.userTypeId = userTypeId;
	}

	public short getUserId() {
		return this.userId;
	}

	public void setUserId(short userId) {
		this.userId = userId;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public Date getBornDat() {
		return this.bornDat;
	}

	public void setBornDat(Date bornDat) {
		this.bornDat = bornDat;
	}
	public Byte getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(Byte userTypeId) {
		this.userTypeId = userTypeId;
	}

	public Usertype getuType() {
		return uType;
	}

	public void Usertype(Usertype uType) {
		this.uType = uType;
	}

	public User() {
	}

}
