package probeHibernate;
// Generated 11-dic-2018 16:27:36 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usertype generated by hbm2java
 */
@Entity
@Table(name="userType")
public class Usertype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name="userTypeId")
	private byte userTypeId;
	@Column(name="utype")
	private String utype;
	@Column(name="description")
	private String description;

	public Usertype() {
	}

	public Usertype(byte userTypeId, String utype) {
		this.userTypeId = userTypeId;
		this.utype = utype;
	}

	public Usertype(byte userTypeId, String utype, String description) {
		this.userTypeId = userTypeId;
		this.utype = utype;
		this.description = description;
	}

	public byte getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(byte userTypeId) {
		this.userTypeId = userTypeId;
	}

	public String getUtype() {
		return this.utype;
	}

	public void setUtype(String utype) {
		this.utype = utype;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
