package entity.copy;
// Generated 15-ene-2019 0:02:31 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Carries generated by hbm2java
 */
@Entity
@Table(name="carries")
public class Carries implements java.io.Serializable {

	private CarriesId id;
	private Authomach authomach;
	private Orderproduct orderproduct;
	private Workstation workstationByDestinyWorkstationId;
	private Workstation workstationByInitialWorkstationId;

	public Carries() {
	}

	public Carries(CarriesId id, Orderproduct orderproduct) {
		this.id = id;
		this.orderproduct = orderproduct;
	}

	public Carries(CarriesId id, Authomach authomach, Orderproduct orderproduct,
			Workstation workstationByDestinyWorkstationId, Workstation workstationByInitialWorkstationId) {
		this.id = id;
		this.authomach = authomach;
		this.orderproduct = orderproduct;
		this.workstationByDestinyWorkstationId = workstationByDestinyWorkstationId;
		this.workstationByInitialWorkstationId = workstationByInitialWorkstationId;
	}

	public CarriesId getId() {
		return this.id;
	}

	public void setId(CarriesId id) {
		this.id = id;
	}

	public Authomach getAuthomach() {
		return this.authomach;
	}

	public void setAuthomach(Authomach authomach) {
		this.authomach = authomach;
	}

	public Orderproduct getOrderproduct() {
		return this.orderproduct;
	}

	public void setOrderproduct(Orderproduct orderproduct) {
		this.orderproduct = orderproduct;
	}

	public Workstation getWorkstationByDestinyWorkstationId() {
		return this.workstationByDestinyWorkstationId;
	}

	public void setWorkstationByDestinyWorkstationId(Workstation workstationByDestinyWorkstationId) {
		this.workstationByDestinyWorkstationId = workstationByDestinyWorkstationId;
	}

	public Workstation getWorkstationByInitialWorkstationId() {
		return this.workstationByInitialWorkstationId;
	}

	public void setWorkstationByInitialWorkstationId(Workstation workstationByInitialWorkstationId) {
		this.workstationByInitialWorkstationId = workstationByInitialWorkstationId;
	}

}
