package entity.copy;
// Generated 15-ene-2019 0:02:31 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user")
public class User implements java.io.Serializable {
	@Id
	@Column(name="userID")
	private int userId;
	@MapsId @ManyToOne
	@JoinColumn(name="usertypeID")
//	@Column(name="usertypeID")
	private Usertype usertype;
	@Column(name="username") //, nullable = false, length=50)
	private String username;
	@Column(name="password")
	private String password;
	@Column(name="name")
	private String name;
	@Column(name="surname")
	private String surname;
	@Column(name="mail")
	private String mail;
	@Column(name="bornDat")
	private Date bornDat;

	public User() {
	}

	public User(String username, String password, String name, String surname, String mail) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.mail = mail;
	}

	public User(Usertype usertype, String username, String password, String name, String surname, String mail,
			Date bornDat) {
		this.usertype = usertype;
		this.username = username;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.mail = mail;
		this.bornDat = bornDat;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Usertype getUsertype() {
		return this.usertype;
	}

	public void setUsertype(Usertype usertype) {
		this.usertype = usertype;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public Date getBornDat() {
		return this.bornDat;
	}

	public void setBornDat(Date bornDat) {
		this.bornDat = bornDat;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.username;
	}

	

}
