package entity;
// Generated 15-ene-2019 0:02:31 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Authomach generated by hbm2java
 */
@Entity
@Table(name="automatch")
public class Authomach implements java.io.Serializable {
	@Id
	@Column(name="machineID")
	private int machineId;
	@Column(name="description")
	private String description;
	@Column(name="state")
	private Boolean state;
	@OneToOne
	@Column(name="workstationActual")
	private Workstation workstationActual;

	public Authomach() {
	}

	public Authomach(String description, Boolean state, Set carrieses) {
		this.description = description;
		this.state = state;
	}

	public int getMachineId() {
		return this.machineId;
	}

	public void setMachineId(int machineId) {
		this.machineId = machineId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getState() {
		return this.state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

}
