package entity;
// Generated 15-ene-2019 0:02:31 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Authomach generated by hbm2java
 */
@Entity
@Table(name="automatch")
public class Authomach implements java.io.Serializable {

	private int machineId;
	private Segment segment;
	private String machine;
	private String description;
	private Boolean state;
	private Set carrieses = new HashSet(0);

	public Authomach() {
	}

	public Authomach(String machine) {
		this.machine = machine;
	}

	public Authomach(Segment segment, String machine, String description, Boolean state, Set carrieses) {
		this.segment = segment;
		this.machine = machine;
		this.description = description;
		this.state = state;
		this.carrieses = carrieses;
	}

	public int getMachineId() {
		return this.machineId;
	}

	public void setMachineId(int machineId) {
		this.machineId = machineId;
	}

	public Segment getSegment() {
		return this.segment;
	}

	public void setSegment(Segment segment) {
		this.segment = segment;
	}

	public String getMachine() {
		return this.machine;
	}

	public void setMachine(String machine) {
		this.machine = machine;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getState() {
		return this.state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

	public Set getCarrieses() {
		return this.carrieses;
	}

	public void setCarrieses(Set carrieses) {
		this.carrieses = carrieses;
	}

}
