package entity;
// Generated 15-ene-2019 0:02:31 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departament generated by hbm2java
 */
@Entity
@Table(name="departament")
public class Departament implements java.io.Serializable {
	@Id
	@Column(name="departamentID")
	private int departamentId;
	@Column(name="departament_name")
	private String departamentName;
	@Column(name="description")
	private String description;

	public Departament() {
	}

	public Departament(String departamentName) {
		this.departamentName = departamentName;
	}

	public Departament(String departamentName, String description) {
		this.departamentName = departamentName;
		this.description = description;
	}

	public int getDepartamentId() {
		return this.departamentId;
	}

	public void setDepartamentId(int departamentId) {
		this.departamentId = departamentId;
	}

	public String getDepartamentName() {
		return this.departamentName;
	}

	public void setDepartamentName(String departamentName) {
		this.departamentName = departamentName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
