package entity;
// Generated 15-ene-2019 0:02:31 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order")
public class Order implements java.io.Serializable {
	@Id
	@Column(name="orderID")
	private int orderId;
	@MapsId @ManyToOne
	@JoinColumn(name="userID")
	//@Column(name="userID")
	private User user;
	@Column(name="dateOrder")
	private Date dateOrder;	
	@Column(name="dateDelivered")
	private Date dateDelivered;	

	public Order() {
	}

	public Order(User user, Date dateOrder) {
		this.user = user;
		this.dateOrder = dateOrder;
		this.dateDelivered = dateDelivered;
	}
	
	public Order(User user, Date dateOrder, Date dateDelivered) {
		this.user = user;
		this.dateOrder = dateOrder;
		this.dateDelivered = dateDelivered;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDateOrder() {
		return dateOrder;
	}

	public void setDateOrder(Date dateOrder) {
		this.dateOrder = dateOrder;
	}

	public Date getDateDelivered() {
		return dateDelivered;
	}

	public void setDateDelivered(Date dateDelivered) {
		this.dateDelivered = dateDelivered;
	}

	


}
