package entity;
// Generated 15-ene-2019 0:02:31 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order")
public class Order implements java.io.Serializable {
	@Id
	@Column(name="orderID")
	private Byte orderId;
	@MapsId @ManyToOne
	@JoinColumn(name="userID")
	//@Column(name="userID")
	private User user;
	@Column(name="date")
	private Date date;	

	public Order() {
	}

	public Order(User user, Date date) {
		this.user = user;
		this.date = date;
	}

	public Byte getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Byte orderId) {
		this.orderId = orderId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}


}
