package entity;
// Generated 15-ene-2019 0:02:31 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Workstation generated by hbm2java
 */
@Entity
@Table(name="workstation")
public class Workstation implements java.io.Serializable {
	@Id
	@Column(name="workstationID")
	private int workstationId;
	@Column(name="description")
	private String description;
	@Column(name="posX")
	private int posX;
	@Column(name="posY")
	private int posY;
	@Column(name="state")
	private Boolean state;

	public Workstation() {
	}

	public Workstation(String description, Boolean state) {
		this.description = description;
		this.state = state;
	}

	public int getWorkstationId() {
		return this.workstationId;
	}

	public void setWorkstationId(int workstationId) {
		this.workstationId = workstationId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getState() {
		return this.state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

	public int getPosX() {
		return posX;
	}

	public void setPosX(int posX) {
		this.posX = posX;
	}

	public int getPosY() {
		return posY;
	}

	public void setPosY(int posY) {
		this.posY = posY;
	}

	
	
}
