package probeHibernate;
// Generated 11-dic-2018 16:27:36 by Hibernate Tools 5.1.0.Alpha1

/**
 * Segment generated by hbm2java
 */
public class Segment implements java.io.Serializable {

	private byte segmentId;
	private String segment;
	private String description;

	public Segment() {
	}

	public Segment(byte segmentId, String segment) {
		this.segmentId = segmentId;
		this.segment = segment;
	}

	public Segment(byte segmentId, String segment, String description) {
		this.segmentId = segmentId;
		this.segment = segment;
		this.description = description;
	}

	public byte getSegmentId() {
		return this.segmentId;
	}

	public void setSegmentId(byte segmentId) {
		this.segmentId = segmentId;
	}

	public String getSegment() {
		return this.segment;
	}

	public void setSegment(String segment) {
		this.segment = segment;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
