package probeHibernate;
// Generated 11-dic-2018 16:27:36 by Hibernate Tools 5.1.0.Alpha1

/**
 * Carries generated by hbm2java
 */
public class Carries implements java.io.Serializable {

	private CarriesId id;

	public Carries() {
	}

	public Carries(CarriesId id) {
		this.id = id;
	}

	public CarriesId getId() {
		return this.id;
	}

	public void setId(CarriesId id) {
		this.id = id;
	}

}
