package probeHibernate;
// Generated 11-dic-2018 16:27:36 by Hibernate Tools 5.1.0.Alpha1

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private short productId;
	private String prodName;
	private float price;
	private int departamentId;

	public Product() {
	}

	public Product(short productId, String prodName) {
		this.productId = productId;
		this.prodName = prodName;
	}

	public Product(String prodName, float price, int departamentId) {
		this.prodName = prodName;
		this.price = price;
		this.departamentId = departamentId;
	}

	public short getProductId() {
		return this.productId;
	}

	public void setProductId(short productId) {
		this.productId = productId;
	}

	public String getProdName() {
		return this.prodName;
	}

	public void setProdName(String prodName) {
		this.prodName = prodName;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public int getDepartamentId() {
		return this.departamentId;
	}

	public void setDepartamentId(int departamentId) {
		this.departamentId = departamentId;
	}

}
