package probeHibernate;
// Generated 11-dic-2018 16:27:36 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user")
public class User implements java.io.Serializable {
	@Id
	@Column(name="userId")
	private short userId;
	@Column(name="uname")
	private String uname;
	@Column(name="password")
	private String password;
	@Column(name="rname")
	private String rname;
	@Column(name="surname")
	private String surname;
	@Column(name="mail")
	private String mail;
	@Column(name="bornDat")
	private String bornDat;
	@Column(name="userTypeId")
	private Byte userTypeId;

	public User() {
	}

	public User(short userId, String uname, String password, String rname, String surname, String mail, String bornDat,
			Byte userTypeId) {
		this.userId = userId;
		this.uname = uname;
		this.password = password;
		this.rname = rname;
		this.surname = surname;
		this.mail = mail;
		this.bornDat = bornDat;
		this.userTypeId = userTypeId;
	}

	public User(String uname, String password, String rname, String surname, String mail, String bornDat,
			Byte userTypeId) {
		this.uname = uname;
		this.password = password;
		this.rname = rname;
		this.surname = surname;
		this.mail = mail;
		this.bornDat = bornDat;
		this.userTypeId = userTypeId;
	}

	public short getUserId() {
		return this.userId;
	}

	public void setUserId(short userId) {
		this.userId = userId;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRname() {
		return this.rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getBornDat() {
		return this.bornDat;
	}

	public void setBornDat(String bornDat) {
		this.bornDat = bornDat;
	}

	public Byte getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(Byte userTypeId) {
		this.userTypeId = userTypeId;
	}
	
	@Override
	public String toString() {
		return this.rname;
	}


}
